apiVersion: v1
kind: Service
metadata:
  name: async
  namespace: default
spec:
  ports:
    - port: 8093		#Service端口
      protocol: TCP	#协议
      targetPort: 8093	#容器端口
      nodePort: 30093	#指定暴露端口号
  selector:
    name: async		#指定关联Pod的标签
  type: NodePort	#服务类型
