apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
spec:
  ports:
    - port: 8090		#Service端口
      protocol: TCP	#协议
      targetPort: 8090	#容器端口
      nodePort: 30090	#指定暴露端口号
  selector:
    name: api		#指定关联Pod的标签
  type: NodePort	#服务类型
