apiVersion: v1
kind: Service
metadata:
  name: query
  namespace: default
spec:
  ports:
    - port: 8092		#Service端口
      protocol: TCP	#协议
      targetPort: 8092	#容器端口
      nodePort: 30092	#指定暴露端口号
  selector:
    name: query		#指定关联Pod的标签
  type: NodePort	#服务类型
